FROM public.ecr.aws/zebrunner/appium:3.0

# Install plugin
RUN appium plugin install images@4.1.0

# Additional tools/dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends libvips-dev && \
    rm -rf /var/lib/apt/lists/*

# Install sharp inside appium context
RUN cd /usr/lib/node_modules/appium && \
    npm install --include=optional sharp@0.34.5

# Check build
RUN cd /usr/lib/node_modules/appium && \
    node -e "console.log(require('sharp').concurrency())" \
