#!/bin/bash

# Appium device container is considered healthy if stf appium up&running. For iOS also WDA status check is needed
# 0 - healthy
# 1 - unhealthy


#Hit the Appium status URL to see if it is available
if curl -Is "http://127.0.0.1:${APPIUM_PORT}/wd/hub/status" | head -1 | grep -q '200 OK'
then
  echo "Appium is up and running."
else
  echo "Appium is unhealthy!"
  exit 1
fi

#214 capture offline state and reconnect
offline=`adb devices | grep -c offline`
if [[ $offline -eq 1 ]]; then
  echo "Device is offline!"
  adb reconnect

  available=`adb devices | grep -c -w device`
  if [[ $available -eq 0 ]]; then
    echo "Device is not accessible after reconnect!"
    exit 1
  fi
fi


# adb status call with ability to exit with error code moved onto he appium

# wda status call moved before session startup to make it at once before testing

#106 status-wda call should be prohibited during the testing

#111 capture panic on wda start and exit from container with error code
# commented healthcheck using ios ps as too fast ios ps can't communicate with device^^^

exit 0
