#!/bin/bash

# Appium device container is considered healthy if stf appium up&running. For iOS also WDA status check is needed
# 0 - healthy
# 1 - unhealthy

# convert to lower case using Linux/Mac compatible syntax (bash v3.2)
PLATFORM_NAME=`echo "$PLATFORM_NAME" |  tr '[:upper:]' '[:lower:]'`
if [[ "$PLATFORM_NAME" == "android" ]]; then
  #Hit the Appium ADB status URL
  if curl -Is "http://127.0.0.1:${APPIUM_PORT}/wd/hub/status-adb" | head -1 | grep -q '200 OK'
  then
    echo "Appium is up and running, adb connection is ok."
    exit 0
  else
    echo "Appium or adb connection is unhelthy!"
    exit 1
  fi
fi


#Hit the Appium status URL to see if it is available
if curl -Is "http://127.0.0.1:${APPIUM_PORT}/wd/hub/status" | head -1 | grep -q '200 OK'
then
  echo "Appium is up and running."
else
  echo "Appium is unhealthy!"
  exit 1
fi

# wda status call moved before session startup to make it at once before testing

#106 status-wda call should be prohibited during the testing

#111 capture panic on wda start and exit from container with error code
# commented healthcheck using ios ps as too fast ios ps can't communicate with device^^^

exit 0
