#!/bin/bash

# Appium device container is considered healthy if stf appium up&running. For iOS also WDA status check is needed
# 0 - healthy
# 1 - unhealthy

#Hit the Appium status URL to see if it is available
if curl -Is "http://127.0.0.1:4723/wd/hub/status" | head -1 | grep -q '200 OK'
then
  echo "[$(date +'%d/%m/%Y %H:%M:%S')] Appium is already running. Nothing to do"
else
  echo "[$(date +'%d/%m/%Y %H:%M:%S')] Appium service is unhealthy!"
  pkill node
  exit 1
fi

exit 0
